### ISSUE TITLE
Implementação e Código do Singleton

### ISSUE THREAD

**Issue by LucasSpinosa** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#1]
### Summary

Singleton é um padrão de projeto cujo objetivo é garantir que uma classe tenha apenas uma única instância na aplicação, fornecendo um ponto de acesso global para a mesma.

### Motivation

É necessário a entrega de pelo menos um Padrão de Projeto Criacional.

### Tasks

- [x] Elaborar cenários de uso do Singleton no brechó em código;
- [x] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [x] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
