### ISSUE TITLE
Implementação e Código do Decorator

### ISSUE THREAD

**Issue by Eduard0803** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#10]
### Summary

Decorator é um padrão de projeto cujo objetivo é permitir que responsabilidades adicionais sejam atribuídas a um objeto dinamicamente, fornecendo uma alternativa flexível à criação de subclasses para estender funcionalidades.

### Tasks

- [x] Elaborar cenários de uso do Decorator no brechó em código;
- [ ] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [x] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
