### ISSUE TITLE
Implementação e Código do Iterator

### ISSUE THREAD

**Issue by LucasSpinosa** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#2]
### Summary

Iterator é um padrão de projeto cujo objetivo é delegar a tarefa de iterar sobre uma estrutura de dados para outro objeto (chamado de Iterator), ao invés de ter métodos para isso na própria estrutura.

### Motivation

É necessário a entrega de pelo menos um Padrão de Projeto Comportamental.

### Tasks

- [ ] Elaborar cenários de uso do Iterator no brechó em código;
- [ ] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [ ] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
