### ISSUE TITLE
Implementação e Código do Builder

### ISSUE THREAD

**Issue by LucasSpinosa** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#3]
### Summary

Builder é um padrão de projeto cujo objetivo é separar a construção de um objeto complexo da sua representação (leia-se: utilização), de modo que a construção pode ser usada para criar diferentes representações.

### Motivation

É necessário a entrega de pelo menos um Padrão de Projeto Criacional.

### Tasks

- [x] Elaborar cenários de uso do Builder no brechó em código;
- [x] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [x] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
