### ISSUE TITLE
Implementação e Código do Prototype

### ISSUE THREAD

**Issue by LucasSpinosa** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#4]
### Summary

Prototype é um padrão de projeto onde o objetivo é criar novos objetos a partir de cópias uma instância já existente.

### Motivation

É necessário a entrega de pelo menos um Padrão de Projeto Criacional.

### Tasks

- [x] Elaborar cenários de uso do Prototype no brechó em código;
- [x] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [x] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
