### ISSUE TITLE
Implementação e Código do Template Method

### ISSUE THREAD

**Issue by LucasSpinosa** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#6]
### Summary

Template Method é um padrão de projeto que define o esqueleto de um algoritmo em uma operação, delegando a definição de alguns passos para subclasses.

### Motivation

É necessário a entrega de pelo menos um Padrão de Projeto Comportamental.

### Tasks

- [x] Elaborar cenários de uso do Template Method no brechó em código;
- [x] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [x] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
