### ISSUE TITLE
Implementação e Código do Composite

### ISSUE THREAD

**Issue by LucasSpinosa** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#7]
### Summary

Composite é um padrão de projeto cujo objetivo é compor objetos como estruturas de árvore para representar hierarquias partes/todo.

### Motivation

É necessário a entrega de pelo menos um Padrão de Projeto Estrutural.

### Tasks

- [x] Elaborar cenários de uso do Composite no brechó em código;
- [x] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [ ] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
