### ISSUE TITLE
Implementação e Código do Adapter

### ISSUE THREAD

**Issue by LucasSpinosa** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#8]
### Summary

Adapter é um padrão de projeto cujo objetivo é adaptar uma interface para uma outra interface esperada pelos clientes.

### Motivation

É necessário a entrega de pelo menos um Padrão de Projeto Estrutural.

### Tasks

- [x] Elaborar cenários de uso do Adapter no brechó em código;
- [x] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [x] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by M4RINH0** [comment]
Adicionado pronto para o pull request
