### ISSUE TITLE
Implementação e Código do Observer

### ISSUE THREAD

**Issue by Eduard0803** [UnBArqDsw2024-2/2024.2_G2_Brecho_Entrega_03#9]
### Summary

Observer é um padrão de projeto cujo objetivo é definir uma dependência um-para-muitos entre objetos, de modo que, quando um objeto for alterado, todos os seus dependentes sejam automaticamente notificados e atualizados.

### Motivation

É necessário a entrega de pelo menos um Padrão de Projeto Comportamental.

### Tasks

- [ ] Elaborar cenários de uso do Observer no brechó em código;
- [ ] Elaborar um texto com as seguinte seções: Introdução, Padrão de Projeto, Implementação e Referências Bibliográficas (citar as referência ao longo do texto);
- [ ] Incluir screenshots do código na documentação.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
